### ISSUE TITLE
ubuntu 16.04 setuptools OSError

### ISSUE THREAD

**Issue by yeago** [whiskerlabs/ansible-python#7]
TASK: [whiskerlabs.python | upgrade packaging tools] **************************
<45.79.9.93> ESTABLISH CONNECTION FOR USER: root
<45.79.9.93> REMOTE_MODULE pip name=setuptools executable=/usr/local/bin/pip state=latest
<45.79.9.93> EXEC sshpass -d8 ssh -C -vvv -o ForwardAgent=yes -o GSSAPIAuthentication=no -o PubkeyAuthentication=no -o User=root -o ConnectTimeout=10 45.79.9.9
3 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
failed: [neomonolith] => (item=setuptools) => {"cmd": "/usr/local/bin/pip install -U setuptools", "failed": true, "item": "setuptools"}
msg: stdout: Collecting setuptools
  Downloading setuptools-21.2.1-py2.py3-none-any.whl (509kB)
Installing collected packages: setuptools
  Found existing installation: setuptools 20.7.0
    Uninstalling setuptools-20.7.0:
      Successfully uninstalled setuptools-20.7.0
Successfully installed setuptools

:stderr: Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/**init**.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/basecommand.py", line 246, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/utils/**init**.py", line 848, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 626, in **init**
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 2080, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1610, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1968, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1848, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/site-packages/pip-8.1.1-py2.7.egg/pip/_vendor/pkg_resources/__init__.py", line 1788, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/setuptools-20.7.0-py2.7.egg'

**Comment by yeago** [comment]
rerun works okay

**Comment by evnm** [comment]
Hello Steve. Thanks for reporting, but this issue is already tracked in #3. The underlying problem lies with pip interacting poorly with certain Linux distributions, which I'd rather not special case from this role. As a workaround, you can either set `python_upgrade_packaging_tools` to False or else upgrade to a new distro in which there are no `setuptools` conflicts.

**Comment by yeago** [comment]
thanks for the tip, i will
